Handlebars templates
Hruchman-Ruslan/bookshop-team-project pull request #5
Opened 2023-04-13 20:49 UTC by Kate-Mil

made 2 templates:
Card template and Best seller block with Css styles

2023-04-13 21:36 UTC, Hruchman-Ruslan requested changes

2023-04-13 21:36 UTC, Hruchman-Ruslan commented on src/partials/home.html
> +<div class="books-gallery">
А де BEM? сlass="books__gallery" і так дальше. Виправ будь ласка

2023-04-14 11:07 UTC, Kate-Mil commented on src/partials/home.html
> +<div class="books-gallery">
изменила. Принимай

2023-04-14 11:16 UTC, Hruchman-Ruslan approved these changes

2023-04-14 11:16 UTC, merged